ARG NODE_VERSION=20.17.0

FROM node:${NODE_VERSION}-slim AS base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base AS build

COPY --link package.json package-lock.json ./
RUN npm install

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]